from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol

from ahq.domain.retail import Order, Product, RetailChange, RetailSnapshot, User, Variant
from ahq.domain.tools import ToolCallRecord


class RetailSession(Protocol):
    async def user(self, user_id: str) -> User | None: ...

    async def user_id_by_email(self, email: str) -> str | None: ...

    async def user_id_by_name_zip(self, first_name: str, last_name: str, zip: str) -> str | None: ...

    async def order(self, order_id: str) -> Order | None: ...

    async def product(self, product_id: str) -> Product | None: ...

    async def variant(self, item_id: str) -> Variant | None: ...

    async def products(self) -> list[Product]: ...

    async def save(self, change: RetailChange) -> None: ...


class RetailRepo(Protocol):
    def session(self) -> AbstractAsyncContextManager[RetailSession]: ...

    async def snapshot(self) -> RetailSnapshot: ...

    async def load(self, snapshot: RetailSnapshot) -> None: ...

    async def recorded_call(self, key: str) -> ToolCallRecord | None: ...
