from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import Literal, Protocol

from ahq.domain.world import KpiDimension, KpiMetric, KpiPoint, Shipment, Ticket, WorldHistory

EmbeddingTarget = Literal["reviews", "ticket_messages"]


class WorldRepo(Protocol):
    async def load(self, history: WorldHistory) -> None: ...

    async def shipments(self) -> list[Shipment]: ...

    async def shipment(self, tracking_id: str) -> Shipment | None: ...

    async def order_dates(self) -> dict[str, datetime]: ...

    async def save_shipment(self, shipment: Shipment) -> bool: ...

    async def open_ticket(self, ticket: Ticket) -> bool: ...

    async def ticket(self, ticket_id: str) -> Ticket | None: ...

    async def tickets_opened(self, since: datetime, until: datetime) -> list[Ticket]: ...

    async def kpis(self, metric: KpiMetric, dimension: KpiDimension, *, days: int) -> list[KpiPoint]: ...

    async def texts_to_embed(self, target: EmbeddingTarget, limit: int) -> list[tuple[str, str]]: ...

    async def save_embeddings(self, target: EmbeddingTarget, vectors: Mapping[str, Sequence[float]]) -> None: ...
